### ISSUE TITLE
avoid using * star imports

### ISSUE THREAD

**Issue by MixoMax** [ExspandSoftware/plastic-gladiator#4]
as PEP 8 States:

> Wildcard imports (from <module> import *) should be avoided, as they make it unclear which names are present in the namespace, confusing both readers and many automated tools.

Not only is it considered best practice to not use wildcard imports, but ruff-vscode also has problems accessing variables and methods imported this way.

![grafik](https://github.com/ExspandSoftware/plastic-gladiator/assets/70818329/e7c23076-99a7-4bb0-ace9-9fe3e985951e)

**Comment by MixoMax** [comment]
[Pep 8](https://peps.python.org/pep-0008/#imports)

**Comment by MisterXYCB** [comment]
Will be avoided for every import except of the config file
